apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-runner
  namespace: gitea-runner
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: gitea-runner
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: 11419680-5338-4f19-bdd9-b422007046af
        property: password
