apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-backup
spec:
  target:
    name: gitea-backup
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        minio_key: "{{ .minio_key }}"
        minio_secret: "{{ .minio_secret }}"
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  data:
    # MinIO credentials
    - secretKey: minio_key
      remoteRef:
        key: dfb2f0c8-110d-4e96-83a7-b49c001c0897
        property: username
    - secretKey: minio_secret
      remoteRef:
        key: dfb2f0c8-110d-4e96-83a7-b49c001c0897
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-config
spec:
  target:
    name: gitea-config
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        database: |-
          USER={{ .dbuser }}
          PASSWD="""{{ .dbpass }}"""
        storage: |-
          MINIO_ACCESS_KEY_ID={{ .minio_nas1_key }}
          MINIO_SECRET_ACCESS_KEY={{ .minio_nas1_secret }}
        #minio_key: "{{ .minio_nas1_key }}"
        #minio_secret: "{{ .minio_nas1_secret }}"
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  data:
    # MinIO credentials for NAS1
    - secretKey: minio_nas1_key
      remoteRef:
        key: 33e8e4e0-eb90-484c-9ec9-b3a8018077a3
        property: username
    - secretKey: minio_nas1_secret
      remoteRef:
        key: 33e8e4e0-eb90-484c-9ec9-b3a8018077a3
        property: password
    # Postgres credentials
    - secretKey: dbuser
      remoteRef:
        key: df47ed61-61d7-4273-b81c-b3a9000de00e
        property: username
    - secretKey: dbpass
      remoteRef:
        key: df47ed61-61d7-4273-b81c-b3a9000de00e
        property: password
