apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-user-gitlab
  namespace: db
spec:
  target:
    name: postgres-user-gitlab
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: |-
          {{ .username }}
        password: |-
          {{ .password }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 5282ad16-c2dc-49d3-8fb3-b2e9012bab57
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 5282ad16-c2dc-49d3-8fb3-b2e9012bab57
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-user-matrix
  namespace: db
spec:
  target:
    name: postgres-user-matrix
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: |-
          {{ .username }}
        password: |-
          {{ .password }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 36d1046b-727e-4e09-a391-b2e90171d3d0
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 36d1046b-727e-4e09-a391-b2e90171d3d0
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-user-pgadmin
  namespace: db
spec:
  target:
    name: postgres-user-pgadmin
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: |-
          {{ .username }}
        password: |-
          {{ .password }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: f333d637-1667-499d-b9a0-b2e9012bd8b7
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: f333d637-1667-499d-b9a0-b2e9012bd8b7
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k3sbackup-externalsecret
  namespace: db
spec:
  target:
    name: k3sbackup-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: |-
          {{ .username }}
        password: |-
          {{ .password }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 685b29c6-9264-4e60-ba4a-b2ea005a5d7b
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 685b29c6-9264-4e60-ba4a-b2ea005a5d7b
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-user-immich
  namespace: db
spec:
  target:
    name: postgres-user-immich
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: |-
          {{ .username }}
        password: |-
          {{ .password }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 5ce63e26-dd7f-46d4-b7ed-b310002ef93f
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 5ce63e26-dd7f-46d4-b7ed-b310002ef93f
        property: password
