namespace: monitoring

resources:
  - namespace.yaml
  - pvc.yaml
  - cluster-role.yaml
  - config.yaml
  - alerts.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - unpoller.yaml
  - kube-state-metrics.yaml
  - restic-secret.yaml
