apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: matrix
  name: dendrite-ingress-tailscale
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: dendrite
      port:
        number: 8008
  tls:
    - hosts:
        - matrix
