apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-user-immich
  namespace: db
spec:
  target:
    name: postgres-user-immich
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: |-
          {{ .username }}
        password: |-
          {{ .password }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 5ce63e26-dd7f-46d4-b7ed-b310002ef93f
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 5ce63e26-dd7f-46d4-b7ed-b310002ef93f
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-user-immich
  namespace: immich
spec:
  target:
    name: postgres-user-immich
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: |-
          {{ .username }}
        password: |-
          {{ .password }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 5ce63e26-dd7f-46d4-b7ed-b310002ef93f
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 5ce63e26-dd7f-46d4-b7ed-b310002ef93f
        property: password
