apiVersion: v1
kind: Namespace
metadata:
  name: kyverno-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: kyverno-system
spec:
  interval: "24h"
  url: "https://kyverno.github.io/kyverno/"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno-system
spec:
  interval: 10m
  chart:
    spec:
      chart: kyverno
      version: "3.4.4"
      sourceRef:
        kind: HelmRepository
        name: kyverno
      interval: "1h"
  values:
    admissionController:
      replicas: 3
    backgroundController:
      replicas: 3
    cleanupController:
      replicas: 2
    reportsController:
      replicas: 2
    crds:
      install: true
