services:
  attic:
    container_name: attic
    image: ghcr.io/zhaofengli/attic:latest
    command: ["-f", "/attic/server.toml"]
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      attic:
      pgattic:
    volumes:
      - /mnt/all/configs/attic/server.toml:/attic/server.toml
      - /mnt/all/containers/attic/data:/attic/storage
    env_file:
      - stack.env
    depends_on:
      pgattic:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://attic:8080 || exit 1",
        ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 15s
    deploy:
      resources:
        reservations:
          cpus: 1.0

  pgattic:
    container_name: pgattic
    image: postgres:17.6-alpine
    restart: unless-stopped
    ports: []
      #- 5432:5432
    networks:
      pgattic:
    volumes:
      - /mnt/all/containers/attic/postgres:/var/lib/postgresql/data
    env_file:
      - stack.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  attic:
  pgattic:
