apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  target:
    name: operator-oauth
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        client_id: |-
          {{ .username }}
        client_secret: |-
          {{ .password }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ffa188a4-63b2-4926-99f0-b33b0021a4f4
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ffa188a4-63b2-4926-99f0-b33b0021a4f4
        property: password
