namespace: db

helmCharts:
  # Install the operator first (with CRDs)
  - name: cloudnative-pg
    repo: "https://cloudnative-pg.github.io/charts/"
    version: "0.23.2"
    namespace: cnpg-system
    releaseName: cnpg
    includeCRDs: true
    valuesInline:
      crds:
        create: true
