namespace: external-secrets

helmCharts:
  # Install the operator first (with CRDs)
  - name: external-secrets
    repo: "https://charts.external-secrets.io/"
    version: "0.17.0"
    namespace: external-secrets
    releaseName: external-secrets
    includeCRDs: true
    valuesInline:
      crds:
        create: true
