apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: gitlab-runner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        runner-registration-token: ""
        runner-token: "{{ .runnerToken }}"
        PACKER_GITHUB_API_TOKEN: "{{ .PACKER_GITHUB_API_TOKEN }}"
        CACHE_S3_SERVER_ADDRESS: "{{ .CACHE_S3_SERVER_ADDRESS }}"
  data:
    - secretKey: runnerToken
      remoteRef:
        key: &key 53719920-b100-4355-8c80-b2f9002fad22
        property: CI_SERVER_TOKEN
    - secretKey: PACKER_GITHUB_API_TOKEN
      remoteRef:
        key: *key
        property: PACKER_GITHUB_API_TOKEN
    - secretKey: CACHE_S3_SERVER_ADDRESS
      remoteRef:
        key: *key
        property: CACHE_S3_SERVER_ADDRESS
        # Includes
        # CI_SERVER_TOKEN
        # PACKER_GITHUB_API_TOKEN
        # CACHE_S3_SERVER_ADDRESS
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-access
  namespace: gitlab-runner
spec:
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: s3-access
    deletionPolicy: Delete
  data:
    - secretKey: username
      remoteRef:
        key: &key 04dd39c2-268d-4a33-aa4c-b1550166139f
        property: username
    - secretKey: password
      remoteRef:
        key: *key
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: image-pull-secrets
  namespace: gitlab-runner
spec:
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: >-
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "username": "{{ .user }}",
                "password": "{{ .password }}",
                "email": "greg.hellings@gmail.com",
                "auth": "{{ .auth }}"
              }
            }
          }
  data:
    - secretKey: user
      remoteRef:
        key: &key f560ae38-368c-4e58-898c-aeb90012d597
        property: username
    - secretKey: password
      remoteRef:
        key: *key
        property: password
    - secretKey: auth
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: *key
        property: auth
