apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-ui
  namespace: longhorn-system
spec:
  target:
    name: longhorn-ui
    deletionPolicy: Delete
    template:
      type: kubernetes.io/basic-auth
      data:
        username: |-
          {{ .username }}
        password: |-
          {{ .password }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: cbf2bf72-c129-437a-8a75-b30f005d29ec
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: cbf2bf72-c129-437a-8a75-b30f005d29ec
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-minio
  namespace: longhorn-system
spec:
  target:
    name: longhorn-minio
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "{{ .username }}"
        AWS_SECRET_ACCESS_KEY: "{{ .password }}"
        AWS_ENDPOINTS: "http://s3.thehellings.lan:9000/"
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: 685b29c6-9264-4e60-ba4a-b2ea005a5d7b
        property: username
    - secretKey: password
      remoteRef:
        key: 685b29c6-9264-4e60-ba4a-b2ea005a5d7b
        property: password
