apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-ui
  namespace: longhorn-system
spec:
  target:
    name: longhorn-ui
    deletionPolicy: Delete
    template:
      type: kubernetes.io/basic-auth
      data:
        username: |-
          {{ .username }}
        password: |-
          {{ .password }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: cbf2bf72-c129-437a-8a75-b30f005d29ec
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: cbf2bf72-c129-437a-8a75-b30f005d29ec
        property: password
