apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-user-pgadmin
  namespace: db
spec:
  target:
    name: postgres-user-pgadmin
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: |-
          {{ .username }}
        password: |-
          {{ .password }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: f333d637-1667-499d-b9a0-b2e9012bd8b7
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: f333d637-1667-499d-b9a0-b2e9012bd8b7
        property: password
