apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-user-matrix
  namespace: db
spec:
  target:
    name: postgres-user-matrix
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: |-
          {{ .username }}
        password: |-
          {{ .password }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 36d1046b-727e-4e09-a391-b2e90171d3d0
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 36d1046b-727e-4e09-a391-b2e90171d3d0
        property: password
