apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-user-gitlab
  namespace: db
spec:
  target:
    name: postgres-user-gitlab
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: |-
          {{ .username }}
        password: |-
          {{ .password }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 5282ad16-c2dc-49d3-8fb3-b2e9012bab57
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 5282ad16-c2dc-49d3-8fb3-b2e9012bab57
        property: password
